### ISSUE TITLE
api.people ORG ID format

### ISSUE THREAD

**Issue by MatNOUVEM** [jeokrohn/wxc_sdk#5]
Hi,

There is an issues in the format of ORG ID in the api.people 
For exemple with uuid NOK :
![image](https://github.com/jeokrohn/wxc_sdk/assets/97040357/0f9ac7fe-bcd2-4276-b94b-ff97c373cd62)

For exemple with webex_id OK :
![image](https://github.com/jeokrohn/wxc_sdk/assets/97040357/724a68c0-c685-47a6-b856-e891390d9f34)

You will need to modify your API to implement the webex_id in all cases. I think that's the best way to solve the problem. 

I have this error when I use your API with uuid: 
![image](https://github.com/jeokrohn/wxc_sdk/assets/97040357/d3d2580b-d749-4443-88e6-24073bbe3000)
But when I use the webex_id it's OK :

**Comment by jeokrohn** [comment]
That is not something that can (nor should) be solved in the SDK. The Webex APIs require ids to be passed in the base64 encoded format as your screenshot from developer.cisco.com clearly shows. The caller has to pass the id (org id in your case) in the correct format.
