### ISSUE TITLE
create.Location() with longitude and Latitude ?

### ISSUE THREAD

**Issue by MatNOUVEM** [jeokrohn/wxc_sdk#6]
Hi,

Could you kindly add the parameters longitude and latitude to the def create location?

The API Webex has these parameters, so if it's possible, I would appreciate it if you could add them.

Thank you in advance. 

Mat

![image](https://github.com/jeokrohn/wxc_sdk/assets/97040357/b76d60b9-7d15-44c2-9d9a-8df5ad7f145a)

**Comment by jeokrohn** [comment]
Great finding. Sorry, this slipped through. Just pushed a commit adding these parameters. Did not push a new release to PyPi yet. So, for now you would need to reference latest in your project requirements.
