### ISSUE TITLE
class DECTDevicesApi(ApiChild, base='telephony/config'): Missing def

### ISSUE THREAD

**Issue by MatNOUVEM** [jeokrohn/wxc_sdk#7]
Hi, 

i don't realy know why but I haven't all definitions in the class DECTDevicesApi. 
![image](https://github.com/jeokrohn/wxc_sdk/assets/97040357/4cdf7336-1054-4b7e-8374-4aea4d738410)

If i go to https://wxc-sdk.readthedocs.io/en/latest/_modules/wxc_sdk/telephony/dect_devices.html#DECTDevicesApi.dect_network_details
 There is more than 4 def . I need the list_dect_networks definition. 

Thank's in advance.

**Comment by jeokrohn** [comment]
You need to make sure that on readthedocs you work with the release of the documentation that matches the release of the SDK you installed.
![RTD version](https://github.com/jeokrohn/wxc_sdk/assets/7795517/1bee2744-b14d-4cc0-9093-9b66c804cdc2)

**Comment by jeokrohn** [comment]
.. or if you want to use latest (unreleased) version of wxc_sdk you can latest as requirement to your pipfile:
$ pipenv install -e git+https://github.com/jeokrohn/wxc_sdk#egg=wxc_sdk

.. and then you should see this in your Pipfile:
[packages]
wxc-sdk = {editable = true, git = "https://github.com/jeokrohn/wxc_sdk"}


If you are using requirements.txt then add this to your requirements.txt:
-e git+https://github.com/jeokrohn/wxc_sdk#egg=wxc-sdk


Also, I pushed release 1.19.0 of the SDK today
